---
- name: Install keepalived
  package:
    name: keepalived
    state: latest
  notify: Restart keepalived

#- name: Identify nic

- name: Allow ESP on Multicast 224.0.0.18
  ansible.builtin.iptables:
    chain: INPUT
    protocol: 51
    destination: 224.0.0.18
    jump: ACCEPT
  become: yes

- name: Allow ICMP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: 1
    jump: ACCEPT
  become: yes


- name: Allow VRRP on Multicast 224.0.0.18
  ansible.builtin.iptables:
    chain: INPUT
    protocol: 112
    destination: 224.0.0.18
    jump: ACCEPT
  become: yes


## Strongly inspired by maas_firewall/tasks/setup_firewall_rules.yaml
- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  changed_when: false

- name: Create /etc/keepalived/conf.d if needed
  ansible.builtin.file:
    path: /etc/keepalived/conf.d
    state: directory
    mode: '0744'

- name: Enable keepalive
  service:
    name: keepalived
    enabled: yes

- name: Template instance configuration conf.d/{{ keepalived_instance_name }}.conf
  template:
    src: keepalived_instance.conf
    dest: "/etc/keepalived/conf.d/{{ keepalived_instance_name }}.conf"
    owner: root
    group: root
    mode: 0640
    backup: yes


- name: Template configuration keepalived.conf
  template:
    src: keepalived_global.conf
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0640
    backup: yes
  notify: Restart keepalived


